# Generated by Django 3.1.5 on 2021-01-31 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('client_name', models.CharField(db_index=True, max_length=255)),
                ('client_email', models.CharField(db_index=True, max_length=255)),
                ('client_phone_number', models.CharField(db_index=True, max_length=255)),
                ('client_shippment_address', models.CharField(db_index=True, max_length=255)),
                ('delivery_fee', models.CharField(max_length=255)),
                ('packaging_fee', models.CharField(max_length=255)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_shipped', models.BooleanField(default=False)),
                ('date_of_delivery', models.DateTimeField()),
                ('date_of_shipment', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED')], max_length=255)),
                ('date_of_payment', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.order')),
            ],
        ),
    ]
